version: '3'
services:
  web:
    container_name: finger-string
    image: morvanabonin/phpnginx:2.0
    volumes:
    - .:/app
    links:
    - mysql
  mysql:
    container_name: finger-string-mysql
    image: mysql/mysql-server:5.7
    volumes:
      - ./data/sql/:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=fingerstring
      - MYSQL_USER=fingerstring
      - MYSQL_PASSWORD=f1ng3r

